

# Default administrative user for all phones
defaultPhoneUser: user
defaultPhonePasswd: pass
defaultPhonePort: 80


# Connection data for SSH'ing RIS DB servers
# See https://www.npmjs.com/package/ssh2 for alternative authentication 
#   methods - just add the data in YAML format here.
# This username/passwd combo is the default for Cisco Communication Manager.
risDBservers:
  - host: 127.0.0.1
    port: 22
    username: ccmadministrator 
    password: Tip@dmin

  - host: anotherserver.local
    port: 22
    username: ccmadministrator 
    password: Tip@dmin


